# Generated by Django 4.2.18 on 2025-08-05 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_videosearchindex_videometadata_searchquery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='analysis_summary',
            new_name='api_cost_tracking',
        ),
        migrations.RemoveField(
            model_name='video',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='video',
            name='features_used',
        ),
        migrations.AddField(
            model_name='video',
            name='chat_analysis_json_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='image_analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='image_analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='total_chat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', '일별'), ('monthly', '월별'), ('yearly', '연별')], default='daily', max_length=10)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('image_analysis_calls', models.IntegerField(default=0)),
                ('text_only_calls', models.IntegerField(default=0)),
                ('model_usage', models.JSONField(default=dict)),
                ('estimated_total_cost', models.FloatField(default=0.0)),
                ('cost_by_type', models.JSONField(default=dict)),
                ('cost_efficiency_score', models.FloatField(default=0.0)),
                ('savings_from_caching', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cost_analysis',
                'indexes': [models.Index(fields=['date', 'period_type'], name='cost_analys_date_59d055_idx'), models.Index(fields=['estimated_total_cost'], name='cost_analys_estimat_f8dae1_idx')],
                'unique_together': {('date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('first_message', models.TextField(blank=True)),
                ('first_message_cost', models.FloatField(default=0.0)),
                ('image_analysis_performed', models.BooleanField(default=False)),
                ('subsequent_messages_cost', models.FloatField(default=0.0)),
                ('models_used', models.JSONField(default=list)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='chat.video')),
            ],
            options={
                'db_table': 'chat_sessions',
                'indexes': [models.Index(fields=['session_id'], name='chat_sessio_session_a3bcba_idx'), models.Index(fields=['started_at'], name='chat_sessio_started_c8e10e_idx')],
            },
        ),
    ]
